default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: sample_dev
  user: sushi
  password: password

production:
  <<: *default
  database: beroot
  username: deploy
  password: password
