meta_name: "Joana Bossa Jewelry"
meta_title: "Joana Bossa Jewelry - Handcrafted jewelry with a story to tell"
meta_description: "Because handmade is the truest way to say loveless..."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@joanabossa"   # required for Twitter Cards
